Fix junit path report

diff --git a/.github/workflows/tests-macos.yml b/.github/workflows/tests-macos.yml
--- a/.github/workflows/tests-macos.yml
+++ b/.github/workflows/tests-macos.yml
@@ -157,6 +157,11 @@ jobs:
         cmake --build build
     - name: Run unit tests
       run: ctest --test-dir build --output-on-failure --timeout 10 --output-junit tests.xml
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: ( success() || failure() ) # always run even if the previous step fails
+      with:
+        report_paths: '${{github.workspace}}/build/tests.xml'
     - name: Run examples
       run: |
         ./build/examples/characteristics_advection
@@ -175,8 +180,3 @@ jobs:
     #       -B build \
     #       -S ./install_test
     #     cmake --build build
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v5
-      if: ( success() || failure() ) # always run even if the previous step fails
-      with:
-        report_paths: '/home/runner/work/ddc/ddc/tests.xml'
